name: flutter_install_referrer
description: Detect from where your application was installed (Google Play, App Store, TestFlight…)
version: 2.1.0
homepage: https://github.com/all-win-solutions/flutter-install-referrer

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.allwinsolutions.flutter_install_referrer
        pluginClass: InstallReferrerPlugin
      ios:
        pluginClass: InstallReferrerPlugin
