// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.allwinsolutions.flutter_install_referrer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

private object InstallReferrerPigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(exception.code, exception.message, exception.details)
    } else {
      listOf(
          exception.javaClass.simpleName,
          exception.toString(),
          "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception))
    }
  }

  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 *
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
    val code: String,
    override val message: String? = null,
    val details: Any? = null
) : RuntimeException()

enum class IRInstallationType(val raw: Int) {
  APP_STORE(0),
  TEST(1),
  DEBUG(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): IRInstallationType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class IRInstallationPlatform(val raw: Int) {
  APPLE_APP_STORE(0),
  APPLE_TESTFLIGHT(1),
  GOOGLE_PLAY(2),
  AMAZON_APP_STORE(3),
  HUAWEI_APP_GALLERY(4),
  OPPO_APP_MARKET(5),
  SAMSUNG_APP_SHOP(6),
  VIVO_APP_STORE(7),
  XIAOMI_APP_STORE(8),
  MANUALLY(9),
  UNKNOWN(10);

  companion object {
    fun ofRaw(raw: Int): IRInstallationPlatform? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class IRPlatform(val raw: Int) {
  IOS(0),
  ANDROID(1);

  companion object {
    fun ofRaw(raw: Int): IRPlatform? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class IRInstallationReferrer(
    val type: IRInstallationType? = null,
    val installationPlatform: IRInstallationPlatform? = null,
    val platform: IRPlatform? = null,
    val packageName: String? = null
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IRInstallationReferrer {
      val type = pigeonVar_list[0] as IRInstallationType?
      val installationPlatform = pigeonVar_list[1] as IRInstallationPlatform?
      val platform = pigeonVar_list[2] as IRPlatform?
      val packageName = pigeonVar_list[3] as String?
      return IRInstallationReferrer(type, installationPlatform, platform, packageName)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        type,
        installationPlatform,
        platform,
        packageName,
    )
  }

  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IRInstallationReferrer
    return InstallReferrerPigeonPigeonUtils.deepEquals(this.type, other.type) &&
        InstallReferrerPigeonPigeonUtils.deepEquals(
            this.installationPlatform, other.installationPlatform) &&
        InstallReferrerPigeonPigeonUtils.deepEquals(this.platform, other.platform) &&
        InstallReferrerPigeonPigeonUtils.deepEquals(this.packageName, other.packageName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + InstallReferrerPigeonPigeonUtils.deepHash(this.type)
    result = 31 * result + InstallReferrerPigeonPigeonUtils.deepHash(this.installationPlatform)
    result = 31 * result + InstallReferrerPigeonPigeonUtils.deepHash(this.platform)
    result = 31 * result + InstallReferrerPigeonPigeonUtils.deepHash(this.packageName)
    return result
  }

  override fun toString(): String {
    return "IRInstallationReferrer(type=$type, installationPlatform=$installationPlatform, platform=$platform, packageName=$packageName)"
  }
}

private open class InstallReferrerPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let { IRInstallationType.ofRaw(it.toInt()) }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let { IRInstallationPlatform.ofRaw(it.toInt()) }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let { IRPlatform.ofRaw(it.toInt()) }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { IRInstallationReferrer.fromList(it) }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is IRInstallationType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is IRInstallationPlatform -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is IRPlatform -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is IRInstallationReferrer -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface InstallReferrerInternalAPI {
  suspend fun detectReferrer(): IRInstallationReferrer

  companion object {
    /** The codec used by InstallReferrerInternalAPI. */
    val codec: MessageCodec<Any?> by lazy { InstallReferrerPigeonPigeonCodec() }

    /**
     * Sets up an instance of `InstallReferrerInternalAPI` to handle messages through the
     * `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
        binaryMessenger: BinaryMessenger,
        api: InstallReferrerInternalAPI?,
        messageChannelSuffix: String = ""
    ) {
      val separatedMessageChannelSuffix =
          if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.flutter_install_referrer.InstallReferrerInternalAPI.detectReferrer$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> =
                  try {
                    listOf(api.detectReferrer())
                  } catch (exception: Throwable) {
                    InstallReferrerPigeonPigeonUtils.wrapError(exception)
                  }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
