// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum SwiftInstallReferrerPigeonPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8_0000_0000_0000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum IRInstallationType: Int, CaseIterable {
  case appStore = 0
  case test = 1
  case debug = 2
  case unknown = 3
}

enum IRInstallationPlatform: Int, CaseIterable {
  case appleAppStore = 0
  case appleTestflight = 1
  case googlePlay = 2
  case amazonAppStore = 3
  case huaweiAppGallery = 4
  case oppoAppMarket = 5
  case samsungAppShop = 6
  case vivoAppStore = 7
  case xiaomiAppStore = 8
  case manually = 9
  case unknown = 10
}

enum IRPlatform: Int, CaseIterable {
  case ios = 0
  case android = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct IRInstallationReferrer: Hashable, CustomStringConvertible {
  var type: IRInstallationType? = nil
  var installationPlatform: IRInstallationPlatform? = nil
  var platform: IRPlatform? = nil
  var packageName: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IRInstallationReferrer? {
    let type: IRInstallationType? = nilOrValue(pigeonVar_list[0])
    let installationPlatform: IRInstallationPlatform? = nilOrValue(pigeonVar_list[1])
    let platform: IRPlatform? = nilOrValue(pigeonVar_list[2])
    let packageName: String? = nilOrValue(pigeonVar_list[3])

    return IRInstallationReferrer(
      type: type,
      installationPlatform: installationPlatform,
      platform: platform,
      packageName: packageName
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      installationPlatform,
      platform,
      packageName,
    ]
  }
  static func == (lhs: IRInstallationReferrer, rhs: IRInstallationReferrer) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SwiftInstallReferrerPigeonPigeonInternal.deepEquals(lhs.type, rhs.type)
      && SwiftInstallReferrerPigeonPigeonInternal.deepEquals(
        lhs.installationPlatform, rhs.installationPlatform)
      && SwiftInstallReferrerPigeonPigeonInternal.deepEquals(lhs.platform, rhs.platform)
      && SwiftInstallReferrerPigeonPigeonInternal.deepEquals(lhs.packageName, rhs.packageName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IRInstallationReferrer")
    SwiftInstallReferrerPigeonPigeonInternal.deepHash(value: type, hasher: &hasher)
    SwiftInstallReferrerPigeonPigeonInternal.deepHash(value: installationPlatform, hasher: &hasher)
    SwiftInstallReferrerPigeonPigeonInternal.deepHash(value: platform, hasher: &hasher)
    SwiftInstallReferrerPigeonPigeonInternal.deepHash(value: packageName, hasher: &hasher)
  }

  public var description: String {
    return
      "IRInstallationReferrer(type: \(String(describing: type)), installationPlatform: \(String(describing: installationPlatform)), platform: \(String(describing: platform)), packageName: \(String(describing: packageName)))"
  }
}

private class SwiftInstallReferrerPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return IRInstallationType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return IRInstallationPlatform(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return IRPlatform(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return IRInstallationReferrer.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SwiftInstallReferrerPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? IRInstallationType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? IRInstallationPlatform {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? IRPlatform {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? IRInstallationReferrer {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SwiftInstallReferrerPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SwiftInstallReferrerPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SwiftInstallReferrerPigeonPigeonCodecWriter(data: data)
  }
}

class SwiftInstallReferrerPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SwiftInstallReferrerPigeonPigeonCodec(
    readerWriter: SwiftInstallReferrerPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol InstallReferrerInternalAPI {
  func detectReferrer() async throws -> IRInstallationReferrer
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class InstallReferrerInternalAPISetup {
  static var codec: FlutterStandardMessageCodec { SwiftInstallReferrerPigeonPigeonCodec.shared }
  /// Sets up an instance of `InstallReferrerInternalAPI` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: InstallReferrerInternalAPI?,
    messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let detectReferrerChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.flutter_install_referrer.InstallReferrerInternalAPI.detectReferrer\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detectReferrerChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.detectReferrer()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      detectReferrerChannel.setMessageHandler(nil)
    }
  }
}
